#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discover.Web.Mvc.Views.Shared.DisplayTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Discover.Common;
    using Discover.Security;
    using Discover.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Web/Mvc/Views/Shared/DisplayTemplates/DateTime.cshtml")]
    public class DateTime : System.Web.Mvc.WebViewPage<Nullable<System.DateTime>      >
    {
        public DateTime()
        {
        }
        public override void Execute()
        {

WriteLiteral("<div class=\"date-time-display multi-input-wrapper\">\r\n    ");


            
            #line 3 "..\..\Web\Mvc\Views\Shared\DisplayTemplates\DateTime.cshtml"
Write(Html.TextBox("", ViewData.Model.HasValue ? ViewData.Model.Value.ToString("dd MMM yyyy") : ViewData.ModelMetadata.NullDisplayText, new { @class = "date", @readonly = true }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 4 "..\..\Web\Mvc\Views\Shared\DisplayTemplates\DateTime.cshtml"
Write(ViewData["DateTimeSeparator"] != null ? ViewData["DateTimeSeparator"].ToString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 5 "..\..\Web\Mvc\Views\Shared\DisplayTemplates\DateTime.cshtml"
Write(Html.TextBox("Hour", ViewData.Model.HasValue ? ViewData.Model.Value.Hour.ToString("00") : ViewData.ModelMetadata.NullDisplayText, new { @class = "hour", @readonly = true }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 6 "..\..\Web\Mvc\Views\Shared\DisplayTemplates\DateTime.cshtml"
Write(Html.TextBox("Minute", ViewData.Model.HasValue ? ViewData.Model.Value.Minute.ToString("00") : ViewData.ModelMetadata.NullDisplayText, new { @class = "minute", @readonly = true }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");


        }
    }
}
#pragma warning restore 1591
