#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discover.Web.Mvc.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Discover.Common;
    using Discover.Security;
    using Discover.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Web/Mvc/Views/Shared/Error.cshtml")]
    public class Error : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Error()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Web\Mvc\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral(@"<div class=""container"">
    <div class=""row"">
        <div class=""twocol""></div>
        <div class=""tencol"">
            <div class=""content"">
                <h1>An error has occurred while processing your request</h1>
                <p>Our engineers have been informed and will investigate the problem.</p>
                <p>Please try again later.</p>
                <p>For further help or information please contact <a href=""mailto:enquiries@discover-corporation.com"">enquiries@discover-corporation.com</a></p>
            </div>
        </div>
        <div class=""twocol last""></div>
    </div>
</div>
");


        }
    }
}
#pragma warning restore 1591
