// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyMood.Web.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected UserController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoveUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetPassword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UnlockUser()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnlockUser);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public UserController Actions { get { return MVC.User; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "User";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "User";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string LogIn = "LogIn";
            public readonly string LogOut = "LogOut";
            public readonly string AccessDenied = "AccessDenied";
            public readonly string ForgottenPassword = "ForgottenPassword";
            public readonly string ChangeMyPassword = "ChangeMyPassword";
            public readonly string ManageUsers = "ManageUsers";
            public readonly string AddUser = "AddUser";
            public readonly string EditUser = "EditUser";
            public readonly string RemoveUser = "RemoveUser";
            public readonly string ResetPassword = "ResetPassword";
            public readonly string UnlockUser = "UnlockUser";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string LogIn = "LogIn";
            public const string LogOut = "LogOut";
            public const string AccessDenied = "AccessDenied";
            public const string ForgottenPassword = "ForgottenPassword";
            public const string ChangeMyPassword = "ChangeMyPassword";
            public const string ManageUsers = "ManageUsers";
            public const string AddUser = "AddUser";
            public const string EditUser = "EditUser";
            public const string RemoveUser = "RemoveUser";
            public const string ResetPassword = "ResetPassword";
            public const string UnlockUser = "UnlockUser";
        }


        static readonly ActionParamsClass_LogIn s_params_LogIn = new ActionParamsClass_LogIn();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogIn LogInParams { get { return s_params_LogIn; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogIn
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ForgottenPassword s_params_ForgottenPassword = new ActionParamsClass_ForgottenPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ForgottenPassword ForgottenPasswordParams { get { return s_params_ForgottenPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ForgottenPassword
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ChangeMyPassword s_params_ChangeMyPassword = new ActionParamsClass_ChangeMyPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeMyPassword ChangeMyPasswordParams { get { return s_params_ChangeMyPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeMyPassword
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_AddUser s_params_AddUser = new ActionParamsClass_AddUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUser AddUserParams { get { return s_params_AddUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUser
        {
            public readonly string model = "NewUser";
        }
        static readonly ActionParamsClass_EditUser s_params_EditUser = new ActionParamsClass_EditUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUser EditUserParams { get { return s_params_EditUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUser
        {
            public readonly string userId = "userId";
            public readonly string model = "ExistingUser";
        }
        static readonly ActionParamsClass_RemoveUser s_params_RemoveUser = new ActionParamsClass_RemoveUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveUser RemoveUserParams { get { return s_params_RemoveUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveUser
        {
            public readonly string userId = "userId";
        }
        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword
        {
            public readonly string userId = "userId";
            public readonly string model = "ResetPassword";
        }
        static readonly ActionParamsClass_UnlockUser s_params_UnlockUser = new ActionParamsClass_UnlockUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnlockUser UnlockUserParams { get { return s_params_UnlockUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnlockUser
        {
            public readonly string userId = "userId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddUser = "AddUser";
                public readonly string ChangeMyPassword = "ChangeMyPassword";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string EditUser = "EditUser";
                public readonly string ForgottenPassword = "ForgottenPassword";
                public readonly string LogIn = "LogIn";
                public readonly string ManageUsers = "ManageUsers";
                public readonly string ResetPassword = "ResetPassword";
            }
            public readonly string AddUser = "~/Views/User/AddUser.cshtml";
            public readonly string ChangeMyPassword = "~/Views/User/ChangeMyPassword.cshtml";
            public readonly string ChangePassword = "~/Views/User/ChangePassword.cshtml";
            public readonly string EditUser = "~/Views/User/EditUser.cshtml";
            public readonly string ForgottenPassword = "~/Views/User/ForgottenPassword.cshtml";
            public readonly string LogIn = "~/Views/User/LogIn.cshtml";
            public readonly string ManageUsers = "~/Views/User/ManageUsers.cshtml";
            public readonly string ResetPassword = "~/Views/User/ResetPassword.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserController : MyMood.Web.Controllers.UserController
    {
        public T4MVC_UserController() : base(Dummy.Instance) { }

        partial void LogInOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult LogIn()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogIn);
            LogInOverride(callInfo);
            return callInfo;
        }

        partial void LogInOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MyMood.Web.Models.UserLogInFormModel model);

        public override System.Web.Mvc.ActionResult LogIn(MyMood.Web.Models.UserLogInFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogIn);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            LogInOverride(callInfo, model);
            return callInfo;
        }

        partial void LogOutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult LogOut()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOut);
            LogOutOverride(callInfo);
            return callInfo;
        }

        partial void AccessDeniedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult AccessDenied()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AccessDenied);
            AccessDeniedOverride(callInfo);
            return callInfo;
        }

        partial void ForgottenPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ForgottenPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgottenPassword);
            ForgottenPasswordOverride(callInfo);
            return callInfo;
        }

        partial void ForgottenPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MyMood.Web.Models.ForgottenPasswordFormModel model);

        public override System.Web.Mvc.ActionResult ForgottenPassword(MyMood.Web.Models.ForgottenPasswordFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgottenPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ForgottenPasswordOverride(callInfo, model);
            return callInfo;
        }

        partial void ChangeMyPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ChangeMyPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeMyPassword);
            ChangeMyPasswordOverride(callInfo);
            return callInfo;
        }

        partial void ChangeMyPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MyMood.Web.Models.ChangePasswordFormModel model);

        public override System.Web.Mvc.ActionResult ChangeMyPassword(MyMood.Web.Models.ChangePasswordFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeMyPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ChangeMyPasswordOverride(callInfo, model);
            return callInfo;
        }

        partial void ManageUsersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ManageUsers()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ManageUsers);
            ManageUsersOverride(callInfo);
            return callInfo;
        }

        partial void AddUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult AddUser()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUser);
            AddUserOverride(callInfo);
            return callInfo;
        }

        partial void AddUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, MyMood.Web.Models.AddUserFormModel model);

        public override System.Web.Mvc.ActionResult AddUser(MyMood.Web.Models.AddUserFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "NewUser", model);
            AddUserOverride(callInfo, model);
            return callInfo;
        }

        partial void EditUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId);

        public override System.Web.Mvc.ActionResult EditUser(System.Guid userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            EditUserOverride(callInfo, userId);
            return callInfo;
        }

        partial void EditUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId, MyMood.Web.Models.EditUserFormModel model);

        public override System.Web.Mvc.ActionResult EditUser(System.Guid userId, MyMood.Web.Models.EditUserFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ExistingUser", model);
            EditUserOverride(callInfo, userId, model);
            return callInfo;
        }

        partial void RemoveUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId);

        public override System.Web.Mvc.ActionResult RemoveUser(System.Guid userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            RemoveUserOverride(callInfo, userId);
            return callInfo;
        }

        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId);

        public override System.Web.Mvc.ActionResult ResetPassword(System.Guid userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ResetPasswordOverride(callInfo, userId);
            return callInfo;
        }

        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId, MyMood.Web.Models.ResetPasswordFormModel model);

        public override System.Web.Mvc.ActionResult ResetPassword(System.Guid userId, MyMood.Web.Models.ResetPasswordFormModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ResetPassword", model);
            ResetPasswordOverride(callInfo, userId, model);
            return callInfo;
        }

        partial void UnlockUserOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Guid userId);

        public override System.Web.Mvc.ActionResult UnlockUser(System.Guid userId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnlockUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            UnlockUserOverride(callInfo, userId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
