#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discover.Web.Mvc.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Discover.Common;
    using Discover.Security;
    using Discover.Web.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Web/Mvc/Views/Shared/EditorTemplates/DateTime.cshtml")]
    public class DateTime : System.Web.Mvc.WebViewPage<Nullable<System.DateTime>>
    {
        public DateTime()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
  
    var hourOptions = ViewData["HourOptions"] as SelectList ?? new SelectList(Enumerable.Range(0, 24).Select(h => new { Value = h, Text = h.ToString("00") }), "Value", "Text", ViewData.Model.HasValue ? ViewData.Model.Value.Hour : 0);
    var minuteStep = (int)(ViewData["MinuteStep"] ?? 1);
    var minuteOptions = ViewData["MinuteOptions"] as SelectList ?? new SelectList(Enumerable.Range(0, 60).Where(m => m % minuteStep == 0).Select(m => new { Value = m, Text = m.ToString("00") }), "Value", "Text", ViewData.Model.HasValue ? ViewData.Model.Value.Minute - (ViewData.Model.Value.Minute % minuteStep) : 0);
        

            
            #line default
            #line hidden
WriteLiteral("<div class=\"date-time-editor multi-input-wrapper ");


            
            #line 7 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
                                             Write(ViewData["class"] as string);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    ");


            
            #line 8 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
Write(Html.TextBox("", ViewData.Model.HasValue ? ViewData.Model.Value.ToString("dd MMM yyyy") : ViewData.ModelMetadata.NullDisplayText, new { @class = "date-picker" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 9 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
Write(ViewData["DateTimeSeparator"] != null ? ViewData["DateTimeSeparator"].ToString() : string.Empty);

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 10 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
Write(Html.DropDownList("Hour", hourOptions, new { @class = "hours" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 11 "..\..\Web\Mvc\Views\Shared\EditorTemplates\DateTime.cshtml"
Write(Html.DropDownList("Minute", minuteOptions, new { @class = "minutes" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");


        }
    }
}
#pragma warning restore 1591
